name: "Lint PR"

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  main:
    name: Validate PR title
    runs-on: arc-runner-set
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
