name: Release Please

on:
  push:
    branches:
      - taiko

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: arc-runner-set
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: simple
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
